name: rockylinux-lemp

services:
  database:
    build:
      context: .
      dockerfile: mysql.dockerfile
    image: lemp-db:1.0.0
    container_name: lemp-db
    hostname: lemp-db
    networks:
      - lemp
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: "America/Chicago"
  web:
    build:
      context: .
      dockerfile: nginx.dockerfile
    image: lemp-web:1.0.0
    container_name: lemp-web
    hostname: lemp-web
    networks:
      - lemp
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/usr/share/nginx/html
    depends_on:
      - database

networks:
  lemp:

volumes:
  db-data:
    driver: local
  web-root:
    driver: local
