name: ubuntu-lamp

services:
  database:
    build:
      context: .
      dockerfile: mysql.dockerfile
    image: lamp-db:1.0.0
    container_name: lamp-db
    hostname: lamp-db
    networks:
      - lamp
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD: 1234
      - TZ: "America/Chicago"
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    image: lamp-web:1.0.0
    container_name: lamp-web
    hostname: lamp-web
    networks:
      - lamp
    ports:
      - 80:80
      - 443:443
      - 21:21
      - 30000:30000
    volumes:
      - web-root:/var/www/html
    depends_on:
      - database
    environment:
      - WEB_ROOT: "/var/www/html"
      - SITE_CONFIG_DIR: "/etc/apache2/sites-available"
      - PHP_MEMORY_LIMIT: "4096M"
      - PHP_POST_MAX_SIZE: "4096M"
      - PHP_UPLOAD_MAX_FILESIZE: "4096M"
      - LOG_PHP_ERROR: "log_errors = On"
      - PHP_LOG_FILE: "error_log = php_errors.log"
      - PHP_INI: "/etc/php/8.1/apache2/php.ini"
      - FTP_USER_PASS: 1234

networks:
  lamp:

volumes:
  db-data:
    driver: local
  web-root:
    driver: local