version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: mysql.dockerfile
    image: lamp-db:1.0.0
    container_name: lamp-db
    hostname: lamp-db
    networks:
      - lamp
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    image: lamp-web:1.0.0
    container_name: lamp-web
    hostname: lamp-web
    networks:
      - lamp
    ports:
      - 80:80
      - 443:443
      - 21:21
      - 30000:30000
    volumes:
      - web-root:/var/www/html
    depends_on:
      - database

networks:
  lamp:

volumes:
  db-data:
    driver: local
  web-root:
    driver: local