name: minio

services:

  minio:
    image: minio/minio
    pull_policy: always
    container_name: minio
    hostname: minio
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001" --address ":9000"

  minio-mc:
    image: minio/mc
    pull_policy: always
    container_name: minio-mc
    hostname: minio-mc
    restart: unless-stopped
    depends_on:
      - minio
    entrypoint: /bin/sh -c "tail -f /dev/null"

  
