name: mediawiki

services:
  mediawiki-web:
    build:
      context: .
      dockerfile: web.dockerfile
    image: mediawiki:alpine-apache-php84-mysql
    container_name: mediawiki-web
    hostname: mediawiki-web
    networks:
      - mediawiki
    volumes:
      - ./data/mediawiki:/var/www/localhost/htdocs
      - ./data/phpinfo.php:/var/www/localhost/htdocs/phpinfo.php
      - ./data/mediawiki.conf:/etc/apache2/conf.d/mediawiki.conf
    depends_on:
      - mediawiki-mysql
    ports:
      - 8080:80

  mediawiki-mysql:
    build:
      context: .
      dockerfile: mysql.dockerfile
    image: mediawiki:ubuntu-mysql-latest
    container_name: mediawiki-mysql
    hostname: mediawiki-mysql
    networks:
      - mediawiki
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      TZ: "America/Chicago"
      MYSQL_ROOT_PASSWORD: "mediawiki"

networks:
  mediawiki:

